apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Emc1992/fleet-test.git
    targetRevision: HEAD
    path: applications/istio

  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    automated:
      prune: true
